#%RAML 1.0 DataType
type: object

properties:
  nombre: string
  creditos: integer
  publico: boolean
  claveMatriculacion: string
  calificacionAprobacion: string
  year: integer
  fechaLimiteInscripcion: datetime
  informacion: string